### ISSUE TITLE
Wrong test value in 04-type-system/03-read-secret-register

### ISSUE THREAD

**Issue by dezse134** [l7mp/learning-go#6]
In my case the second generated test was:
```go
a, b, c, d = parseChannelControlRegister(0xdeadbeef)
assert.Equal(t, []byte{0xDE, 0xAD, 0xDE, 0xEF}, []byte{a, b, c, d})
```
This is wrong because the third byte should be `0xBE` instead of `0xDE`.
This can be fixed in `exercise.yaml` line 11.
https://github.com/l7mp/learning-go/blob/9086577e41c14c8f7d9cb7d827a2045a961affcc/04-type-system/03-read-secret-register/exercise.yaml#L11

**Comment by levaitamas** [comment]
Nice catch! Thanks @dezse134! Fixed in d70a064.
