### ISSUE TITLE
Lab02 first test run wrong tag

### ISSUE THREAD

**Issue by dezse134** [l7mp/learning-go#7]
After configuring the program to include the hostname in the response the test command is:
`go test ./... --tags=helloworld -v -count 1`

https://github.com/dezse134/learning-go/blob/3d552a0f033c95c4c4cd6b6f202d6245fc4f843f/99-labs/02-webapps/README.md?plain=1#L92

That tag is wrong because it runs the other test that tests the final version of the program with the go version in the response. The actual tag should be `main` because that's actually the proper (and currently unused) test in the directory.

**Comment by rg0now** [comment]
This should have already been fixed in https://github.com/l7mp/learning-go/commit/7da551f1fb20a365cb71fdd42e396d76687a304c, can you please pull-rebase and double-check?

**Comment by dezse134** [comment]
I did the rebase and tested with the new tests.

Did what the [first exercise](https://github.com/l7mp/learning-go/tree/master/99-labs/02-webapps#exercise) said: returned hello with hostname with a newline as last character and tested with `tags=helloworldhostname`, the test failed.

After a little experimenting these are the possible solutions:
1. Remove the newline from the response string, this would be the easiest one
2. Remove the `$` from the [line](https://github.com/l7mp/learning-go/blob/bd3a86b5db8641c5f18b303501f2e356b1bd8406/99-labs/code/helloworld/helloworld_with_hostname_test.go#L21), bacause the `\n` character won't match the `.*` expression so the remaining endline won't match the end of line symbol `$`
3. Add either the `m` or `s` flag in the [regexp line](https://github.com/l7mp/learning-go/blob/bd3a86b5db8641c5f18b303501f2e356b1bd8406/99-labs/code/helloworld/helloworld_with_hostname_test.go#L21)
    - `m` multiline flag matches newlines as endings so the `$` will match
    - `s` single line (or dotall) flag will make the `.*` match the `\n` too so the whole string is consumed before the `$`

    These can be added like this:
    ```go
    r := regexp.MustCompile("(?s)^Hello world from .*$")
    ```
    or
    ```go
    r := regexp.MustCompile("(?m)^Hello world from .*$")
    ```

The first solution would leave the tests untouched and would require the modification of only two markdown line: [#1](https://github.com/l7mp/learning-go/blob/bd3a86b5db8641c5f18b303501f2e356b1bd8406/99-labs/02-webapps/README.md?plain=1#L45) and [#2](https://github.com/l7mp/learning-go/blob/bd3a86b5db8641c5f18b303501f2e356b1bd8406/99-labs/02-webapps/README.md?plain=1#L86)

The other test with the go version included seems to work.

**Comment by rg0now** [comment]
Thx! People complained about the lack of the newline so I'd rule solution (1) out, and (3) seems a bit of an overkill. Can you please submit a PR implementing idea (2)?

**Comment by rg0now** [comment]
I pushed a quick [fix](https://github.com/l7mp/learning-go/commit/e09ca0a961b5d419de0736197dd0aca2ea3f38cf), can you please check?

**Comment by dezse134** [comment]
Just checked it, works fine on my side.
